# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/perry/dev/extras

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/perry/dev/extras/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/perry/dev/extras/build/CMakeFiles /home/perry/dev/extras/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/perry/dev/extras/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/perry/dev/extras/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named extras

# Build rule for target.
extras: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extras
.PHONY : extras

# fast build rule for target.
extras/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/build
.PHONY : extras/fast

#=============================================================================
# Target rules for targets named run-unittests-extras

# Build rule for target.
run-unittests-extras: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run-unittests-extras
.PHONY : run-unittests-extras

# fast build rule for target.
run-unittests-extras/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/build
.PHONY : run-unittests-extras/fast

src/crcs/crc.o: src/crcs/crc.cpp.o
.PHONY : src/crcs/crc.o

# target to build an object file
src/crcs/crc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc.cpp.o
.PHONY : src/crcs/crc.cpp.o

src/crcs/crc.i: src/crcs/crc.cpp.i
.PHONY : src/crcs/crc.i

# target to preprocess a source file
src/crcs/crc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc.cpp.i
.PHONY : src/crcs/crc.cpp.i

src/crcs/crc.s: src/crcs/crc.cpp.s
.PHONY : src/crcs/crc.s

# target to generate assembly for a file
src/crcs/crc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc.cpp.s
.PHONY : src/crcs/crc.cpp.s

src/crcs/crc16.o: src/crcs/crc16.cpp.o
.PHONY : src/crcs/crc16.o

# target to build an object file
src/crcs/crc16.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc16.cpp.o
.PHONY : src/crcs/crc16.cpp.o

src/crcs/crc16.i: src/crcs/crc16.cpp.i
.PHONY : src/crcs/crc16.i

# target to preprocess a source file
src/crcs/crc16.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc16.cpp.i
.PHONY : src/crcs/crc16.cpp.i

src/crcs/crc16.s: src/crcs/crc16.cpp.s
.PHONY : src/crcs/crc16.s

# target to generate assembly for a file
src/crcs/crc16.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc16.cpp.s
.PHONY : src/crcs/crc16.cpp.s

src/crcs/crc32.o: src/crcs/crc32.cpp.o
.PHONY : src/crcs/crc32.o

# target to build an object file
src/crcs/crc32.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc32.cpp.o
.PHONY : src/crcs/crc32.cpp.o

src/crcs/crc32.i: src/crcs/crc32.cpp.i
.PHONY : src/crcs/crc32.i

# target to preprocess a source file
src/crcs/crc32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc32.cpp.i
.PHONY : src/crcs/crc32.cpp.i

src/crcs/crc32.s: src/crcs/crc32.cpp.s
.PHONY : src/crcs/crc32.s

# target to generate assembly for a file
src/crcs/crc32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc32.cpp.s
.PHONY : src/crcs/crc32.cpp.s

src/crcs/crc64.o: src/crcs/crc64.cpp.o
.PHONY : src/crcs/crc64.o

# target to build an object file
src/crcs/crc64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc64.cpp.o
.PHONY : src/crcs/crc64.cpp.o

src/crcs/crc64.i: src/crcs/crc64.cpp.i
.PHONY : src/crcs/crc64.i

# target to preprocess a source file
src/crcs/crc64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc64.cpp.i
.PHONY : src/crcs/crc64.cpp.i

src/crcs/crc64.s: src/crcs/crc64.cpp.s
.PHONY : src/crcs/crc64.s

# target to generate assembly for a file
src/crcs/crc64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/crcs/crc64.cpp.s
.PHONY : src/crcs/crc64.cpp.s

src/devices/ansi_colors.o: src/devices/ansi_colors.cpp.o
.PHONY : src/devices/ansi_colors.o

# target to build an object file
src/devices/ansi_colors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/devices/ansi_colors.cpp.o
.PHONY : src/devices/ansi_colors.cpp.o

src/devices/ansi_colors.i: src/devices/ansi_colors.cpp.i
.PHONY : src/devices/ansi_colors.i

# target to preprocess a source file
src/devices/ansi_colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/devices/ansi_colors.cpp.i
.PHONY : src/devices/ansi_colors.cpp.i

src/devices/ansi_colors.s: src/devices/ansi_colors.cpp.s
.PHONY : src/devices/ansi_colors.s

# target to generate assembly for a file
src/devices/ansi_colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/devices/ansi_colors.cpp.s
.PHONY : src/devices/ansi_colors.cpp.s

src/devices/dotenv.o: src/devices/dotenv.cpp.o
.PHONY : src/devices/dotenv.o

# target to build an object file
src/devices/dotenv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/devices/dotenv.cpp.o
.PHONY : src/devices/dotenv.cpp.o

src/devices/dotenv.i: src/devices/dotenv.cpp.i
.PHONY : src/devices/dotenv.i

# target to preprocess a source file
src/devices/dotenv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/devices/dotenv.cpp.i
.PHONY : src/devices/dotenv.cpp.i

src/devices/dotenv.s: src/devices/dotenv.cpp.s
.PHONY : src/devices/dotenv.s

# target to generate assembly for a file
src/devices/dotenv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/devices/dotenv.cpp.s
.PHONY : src/devices/dotenv.cpp.s

src/exceptions.o: src/exceptions.cpp.o
.PHONY : src/exceptions.o

# target to build an object file
src/exceptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/exceptions.cpp.o
.PHONY : src/exceptions.cpp.o

src/exceptions.i: src/exceptions.cpp.i
.PHONY : src/exceptions.i

# target to preprocess a source file
src/exceptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/exceptions.cpp.i
.PHONY : src/exceptions.cpp.i

src/exceptions.s: src/exceptions.cpp.s
.PHONY : src/exceptions.s

# target to generate assembly for a file
src/exceptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/exceptions.cpp.s
.PHONY : src/exceptions.cpp.s

src/file/assertions.o: src/file/assertions.cpp.o
.PHONY : src/file/assertions.o

# target to build an object file
src/file/assertions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/assertions.cpp.o
.PHONY : src/file/assertions.cpp.o

src/file/assertions.i: src/file/assertions.cpp.i
.PHONY : src/file/assertions.i

# target to preprocess a source file
src/file/assertions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/assertions.cpp.i
.PHONY : src/file/assertions.cpp.i

src/file/assertions.s: src/file/assertions.cpp.s
.PHONY : src/file/assertions.s

# target to generate assembly for a file
src/file/assertions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/assertions.cpp.s
.PHONY : src/file/assertions.cpp.s

src/file/construct.o: src/file/construct.cpp.o
.PHONY : src/file/construct.o

# target to build an object file
src/file/construct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/construct.cpp.o
.PHONY : src/file/construct.cpp.o

src/file/construct.i: src/file/construct.cpp.i
.PHONY : src/file/construct.i

# target to preprocess a source file
src/file/construct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/construct.cpp.i
.PHONY : src/file/construct.cpp.i

src/file/construct.s: src/file/construct.cpp.s
.PHONY : src/file/construct.s

# target to generate assembly for a file
src/file/construct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/construct.cpp.s
.PHONY : src/file/construct.cpp.s

src/file/methods.o: src/file/methods.cpp.o
.PHONY : src/file/methods.o

# target to build an object file
src/file/methods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/methods.cpp.o
.PHONY : src/file/methods.cpp.o

src/file/methods.i: src/file/methods.cpp.i
.PHONY : src/file/methods.i

# target to preprocess a source file
src/file/methods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/methods.cpp.i
.PHONY : src/file/methods.cpp.i

src/file/methods.s: src/file/methods.cpp.s
.PHONY : src/file/methods.s

# target to generate assembly for a file
src/file/methods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/file/methods.cpp.s
.PHONY : src/file/methods.cpp.s

src/filesystem/files.o: src/filesystem/files.cpp.o
.PHONY : src/filesystem/files.o

# target to build an object file
src/filesystem/files.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/files.cpp.o
.PHONY : src/filesystem/files.cpp.o

src/filesystem/files.i: src/filesystem/files.cpp.i
.PHONY : src/filesystem/files.i

# target to preprocess a source file
src/filesystem/files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/files.cpp.i
.PHONY : src/filesystem/files.cpp.i

src/filesystem/files.s: src/filesystem/files.cpp.s
.PHONY : src/filesystem/files.s

# target to generate assembly for a file
src/filesystem/files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/files.cpp.s
.PHONY : src/filesystem/files.cpp.s

src/filesystem/filesystem.o: src/filesystem/filesystem.cpp.o
.PHONY : src/filesystem/filesystem.o

# target to build an object file
src/filesystem/filesystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/filesystem.cpp.o
.PHONY : src/filesystem/filesystem.cpp.o

src/filesystem/filesystem.i: src/filesystem/filesystem.cpp.i
.PHONY : src/filesystem/filesystem.i

# target to preprocess a source file
src/filesystem/filesystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/filesystem.cpp.i
.PHONY : src/filesystem/filesystem.cpp.i

src/filesystem/filesystem.s: src/filesystem/filesystem.cpp.s
.PHONY : src/filesystem/filesystem.s

# target to generate assembly for a file
src/filesystem/filesystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/filesystem.cpp.s
.PHONY : src/filesystem/filesystem.cpp.s

src/filesystem/paths.o: src/filesystem/paths.cpp.o
.PHONY : src/filesystem/paths.o

# target to build an object file
src/filesystem/paths.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/paths.cpp.o
.PHONY : src/filesystem/paths.cpp.o

src/filesystem/paths.i: src/filesystem/paths.cpp.i
.PHONY : src/filesystem/paths.i

# target to preprocess a source file
src/filesystem/paths.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/paths.cpp.i
.PHONY : src/filesystem/paths.cpp.i

src/filesystem/paths.s: src/filesystem/paths.cpp.s
.PHONY : src/filesystem/paths.s

# target to generate assembly for a file
src/filesystem/paths.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/paths.cpp.s
.PHONY : src/filesystem/paths.cpp.s

src/filesystem/system.o: src/filesystem/system.cpp.o
.PHONY : src/filesystem/system.o

# target to build an object file
src/filesystem/system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/system.cpp.o
.PHONY : src/filesystem/system.cpp.o

src/filesystem/system.i: src/filesystem/system.cpp.i
.PHONY : src/filesystem/system.i

# target to preprocess a source file
src/filesystem/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/system.cpp.i
.PHONY : src/filesystem/system.cpp.i

src/filesystem/system.s: src/filesystem/system.cpp.s
.PHONY : src/filesystem/system.s

# target to generate assembly for a file
src/filesystem/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/filesystem/system.cpp.s
.PHONY : src/filesystem/system.cpp.s

src/status/StatusLine.o: src/status/StatusLine.cpp.o
.PHONY : src/status/StatusLine.o

# target to build an object file
src/status/StatusLine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/status/StatusLine.cpp.o
.PHONY : src/status/StatusLine.cpp.o

src/status/StatusLine.i: src/status/StatusLine.cpp.i
.PHONY : src/status/StatusLine.i

# target to preprocess a source file
src/status/StatusLine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/status/StatusLine.cpp.i
.PHONY : src/status/StatusLine.cpp.i

src/status/StatusLine.s: src/status/StatusLine.cpp.s
.PHONY : src/status/StatusLine.s

# target to generate assembly for a file
src/status/StatusLine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/status/StatusLine.cpp.s
.PHONY : src/status/StatusLine.cpp.s

src/strings/string_support.o: src/strings/string_support.cpp.o
.PHONY : src/strings/string_support.o

# target to build an object file
src/strings/string_support.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/strings/string_support.cpp.o
.PHONY : src/strings/string_support.cpp.o

src/strings/string_support.i: src/strings/string_support.cpp.i
.PHONY : src/strings/string_support.i

# target to preprocess a source file
src/strings/string_support.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/strings/string_support.cpp.i
.PHONY : src/strings/string_support.cpp.i

src/strings/string_support.s: src/strings/string_support.cpp.s
.PHONY : src/strings/string_support.s

# target to generate assembly for a file
src/strings/string_support.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/strings/string_support.cpp.s
.PHONY : src/strings/string_support.cpp.s

src/strings/strings.o: src/strings/strings.cpp.o
.PHONY : src/strings/strings.o

# target to build an object file
src/strings/strings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/strings/strings.cpp.o
.PHONY : src/strings/strings.cpp.o

src/strings/strings.i: src/strings/strings.cpp.i
.PHONY : src/strings/strings.i

# target to preprocess a source file
src/strings/strings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/strings/strings.cpp.i
.PHONY : src/strings/strings.cpp.i

src/strings/strings.s: src/strings/strings.cpp.s
.PHONY : src/strings/strings.s

# target to generate assembly for a file
src/strings/strings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extras.dir/build.make CMakeFiles/extras.dir/src/strings/strings.cpp.s
.PHONY : src/strings/strings.cpp.s

test/interfaces/crcs/dock_octal.o: test/interfaces/crcs/dock_octal.cpp.o
.PHONY : test/interfaces/crcs/dock_octal.o

# target to build an object file
test/interfaces/crcs/dock_octal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/dock_octal.cpp.o
.PHONY : test/interfaces/crcs/dock_octal.cpp.o

test/interfaces/crcs/dock_octal.i: test/interfaces/crcs/dock_octal.cpp.i
.PHONY : test/interfaces/crcs/dock_octal.i

# target to preprocess a source file
test/interfaces/crcs/dock_octal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/dock_octal.cpp.i
.PHONY : test/interfaces/crcs/dock_octal.cpp.i

test/interfaces/crcs/dock_octal.s: test/interfaces/crcs/dock_octal.cpp.s
.PHONY : test/interfaces/crcs/dock_octal.s

# target to generate assembly for a file
test/interfaces/crcs/dock_octal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/dock_octal.cpp.s
.PHONY : test/interfaces/crcs/dock_octal.cpp.s

test/interfaces/crcs/test_crc32.o: test/interfaces/crcs/test_crc32.cpp.o
.PHONY : test/interfaces/crcs/test_crc32.o

# target to build an object file
test/interfaces/crcs/test_crc32.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crc32.cpp.o
.PHONY : test/interfaces/crcs/test_crc32.cpp.o

test/interfaces/crcs/test_crc32.i: test/interfaces/crcs/test_crc32.cpp.i
.PHONY : test/interfaces/crcs/test_crc32.i

# target to preprocess a source file
test/interfaces/crcs/test_crc32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crc32.cpp.i
.PHONY : test/interfaces/crcs/test_crc32.cpp.i

test/interfaces/crcs/test_crc32.s: test/interfaces/crcs/test_crc32.cpp.s
.PHONY : test/interfaces/crcs/test_crc32.s

# target to generate assembly for a file
test/interfaces/crcs/test_crc32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crc32.cpp.s
.PHONY : test/interfaces/crcs/test_crc32.cpp.s

test/interfaces/crcs/test_crc64.o: test/interfaces/crcs/test_crc64.cpp.o
.PHONY : test/interfaces/crcs/test_crc64.o

# target to build an object file
test/interfaces/crcs/test_crc64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crc64.cpp.o
.PHONY : test/interfaces/crcs/test_crc64.cpp.o

test/interfaces/crcs/test_crc64.i: test/interfaces/crcs/test_crc64.cpp.i
.PHONY : test/interfaces/crcs/test_crc64.i

# target to preprocess a source file
test/interfaces/crcs/test_crc64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crc64.cpp.i
.PHONY : test/interfaces/crcs/test_crc64.cpp.i

test/interfaces/crcs/test_crc64.s: test/interfaces/crcs/test_crc64.cpp.s
.PHONY : test/interfaces/crcs/test_crc64.s

# target to generate assembly for a file
test/interfaces/crcs/test_crc64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crc64.cpp.s
.PHONY : test/interfaces/crcs/test_crc64.cpp.s

test/interfaces/crcs/test_crcs.o: test/interfaces/crcs/test_crcs.cpp.o
.PHONY : test/interfaces/crcs/test_crcs.o

# target to build an object file
test/interfaces/crcs/test_crcs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crcs.cpp.o
.PHONY : test/interfaces/crcs/test_crcs.cpp.o

test/interfaces/crcs/test_crcs.i: test/interfaces/crcs/test_crcs.cpp.i
.PHONY : test/interfaces/crcs/test_crcs.i

# target to preprocess a source file
test/interfaces/crcs/test_crcs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crcs.cpp.i
.PHONY : test/interfaces/crcs/test_crcs.cpp.i

test/interfaces/crcs/test_crcs.s: test/interfaces/crcs/test_crcs.cpp.s
.PHONY : test/interfaces/crcs/test_crcs.s

# target to generate assembly for a file
test/interfaces/crcs/test_crcs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/crcs/test_crcs.cpp.s
.PHONY : test/interfaces/crcs/test_crcs.cpp.s

test/interfaces/devices/dock_dotenv.o: test/interfaces/devices/dock_dotenv.cpp.o
.PHONY : test/interfaces/devices/dock_dotenv.o

# target to build an object file
test/interfaces/devices/dock_dotenv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/devices/dock_dotenv.cpp.o
.PHONY : test/interfaces/devices/dock_dotenv.cpp.o

test/interfaces/devices/dock_dotenv.i: test/interfaces/devices/dock_dotenv.cpp.i
.PHONY : test/interfaces/devices/dock_dotenv.i

# target to preprocess a source file
test/interfaces/devices/dock_dotenv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/devices/dock_dotenv.cpp.i
.PHONY : test/interfaces/devices/dock_dotenv.cpp.i

test/interfaces/devices/dock_dotenv.s: test/interfaces/devices/dock_dotenv.cpp.s
.PHONY : test/interfaces/devices/dock_dotenv.s

# target to generate assembly for a file
test/interfaces/devices/dock_dotenv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/devices/dock_dotenv.cpp.s
.PHONY : test/interfaces/devices/dock_dotenv.cpp.s

test/interfaces/devices/test_dotenv.o: test/interfaces/devices/test_dotenv.cpp.o
.PHONY : test/interfaces/devices/test_dotenv.o

# target to build an object file
test/interfaces/devices/test_dotenv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/devices/test_dotenv.cpp.o
.PHONY : test/interfaces/devices/test_dotenv.cpp.o

test/interfaces/devices/test_dotenv.i: test/interfaces/devices/test_dotenv.cpp.i
.PHONY : test/interfaces/devices/test_dotenv.i

# target to preprocess a source file
test/interfaces/devices/test_dotenv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/devices/test_dotenv.cpp.i
.PHONY : test/interfaces/devices/test_dotenv.cpp.i

test/interfaces/devices/test_dotenv.s: test/interfaces/devices/test_dotenv.cpp.s
.PHONY : test/interfaces/devices/test_dotenv.s

# target to generate assembly for a file
test/interfaces/devices/test_dotenv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/devices/test_dotenv.cpp.s
.PHONY : test/interfaces/devices/test_dotenv.cpp.s

test/interfaces/etc/dock_interface.o: test/interfaces/etc/dock_interface.cpp.o
.PHONY : test/interfaces/etc/dock_interface.o

# target to build an object file
test/interfaces/etc/dock_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/etc/dock_interface.cpp.o
.PHONY : test/interfaces/etc/dock_interface.cpp.o

test/interfaces/etc/dock_interface.i: test/interfaces/etc/dock_interface.cpp.i
.PHONY : test/interfaces/etc/dock_interface.i

# target to preprocess a source file
test/interfaces/etc/dock_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/etc/dock_interface.cpp.i
.PHONY : test/interfaces/etc/dock_interface.cpp.i

test/interfaces/etc/dock_interface.s: test/interfaces/etc/dock_interface.cpp.s
.PHONY : test/interfaces/etc/dock_interface.s

# target to generate assembly for a file
test/interfaces/etc/dock_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/etc/dock_interface.cpp.s
.PHONY : test/interfaces/etc/dock_interface.cpp.s

test/interfaces/file/dock_interface.o: test/interfaces/file/dock_interface.cpp.o
.PHONY : test/interfaces/file/dock_interface.o

# target to build an object file
test/interfaces/file/dock_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/dock_interface.cpp.o
.PHONY : test/interfaces/file/dock_interface.cpp.o

test/interfaces/file/dock_interface.i: test/interfaces/file/dock_interface.cpp.i
.PHONY : test/interfaces/file/dock_interface.i

# target to preprocess a source file
test/interfaces/file/dock_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/dock_interface.cpp.i
.PHONY : test/interfaces/file/dock_interface.cpp.i

test/interfaces/file/dock_interface.s: test/interfaces/file/dock_interface.cpp.s
.PHONY : test/interfaces/file/dock_interface.s

# target to generate assembly for a file
test/interfaces/file/dock_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/dock_interface.cpp.s
.PHONY : test/interfaces/file/dock_interface.cpp.s

test/interfaces/file/mold_assertions.o: test/interfaces/file/mold_assertions.cpp.o
.PHONY : test/interfaces/file/mold_assertions.o

# target to build an object file
test/interfaces/file/mold_assertions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/mold_assertions.cpp.o
.PHONY : test/interfaces/file/mold_assertions.cpp.o

test/interfaces/file/mold_assertions.i: test/interfaces/file/mold_assertions.cpp.i
.PHONY : test/interfaces/file/mold_assertions.i

# target to preprocess a source file
test/interfaces/file/mold_assertions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/mold_assertions.cpp.i
.PHONY : test/interfaces/file/mold_assertions.cpp.i

test/interfaces/file/mold_assertions.s: test/interfaces/file/mold_assertions.cpp.s
.PHONY : test/interfaces/file/mold_assertions.s

# target to generate assembly for a file
test/interfaces/file/mold_assertions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/mold_assertions.cpp.s
.PHONY : test/interfaces/file/mold_assertions.cpp.s

test/interfaces/file/test_cases.o: test/interfaces/file/test_cases.cpp.o
.PHONY : test/interfaces/file/test_cases.o

# target to build an object file
test/interfaces/file/test_cases.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/test_cases.cpp.o
.PHONY : test/interfaces/file/test_cases.cpp.o

test/interfaces/file/test_cases.i: test/interfaces/file/test_cases.cpp.i
.PHONY : test/interfaces/file/test_cases.i

# target to preprocess a source file
test/interfaces/file/test_cases.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/test_cases.cpp.i
.PHONY : test/interfaces/file/test_cases.cpp.i

test/interfaces/file/test_cases.s: test/interfaces/file/test_cases.cpp.s
.PHONY : test/interfaces/file/test_cases.s

# target to generate assembly for a file
test/interfaces/file/test_cases.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/file/test_cases.cpp.s
.PHONY : test/interfaces/file/test_cases.cpp.s

test/interfaces/filesystem/dock_paths.o: test/interfaces/filesystem/dock_paths.cpp.o
.PHONY : test/interfaces/filesystem/dock_paths.o

# target to build an object file
test/interfaces/filesystem/dock_paths.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/dock_paths.cpp.o
.PHONY : test/interfaces/filesystem/dock_paths.cpp.o

test/interfaces/filesystem/dock_paths.i: test/interfaces/filesystem/dock_paths.cpp.i
.PHONY : test/interfaces/filesystem/dock_paths.i

# target to preprocess a source file
test/interfaces/filesystem/dock_paths.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/dock_paths.cpp.i
.PHONY : test/interfaces/filesystem/dock_paths.cpp.i

test/interfaces/filesystem/dock_paths.s: test/interfaces/filesystem/dock_paths.cpp.s
.PHONY : test/interfaces/filesystem/dock_paths.s

# target to generate assembly for a file
test/interfaces/filesystem/dock_paths.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/dock_paths.cpp.s
.PHONY : test/interfaces/filesystem/dock_paths.cpp.s

test/interfaces/filesystem/path/dock_path.o: test/interfaces/filesystem/path/dock_path.cpp.o
.PHONY : test/interfaces/filesystem/path/dock_path.o

# target to build an object file
test/interfaces/filesystem/path/dock_path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/path/dock_path.cpp.o
.PHONY : test/interfaces/filesystem/path/dock_path.cpp.o

test/interfaces/filesystem/path/dock_path.i: test/interfaces/filesystem/path/dock_path.cpp.i
.PHONY : test/interfaces/filesystem/path/dock_path.i

# target to preprocess a source file
test/interfaces/filesystem/path/dock_path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/path/dock_path.cpp.i
.PHONY : test/interfaces/filesystem/path/dock_path.cpp.i

test/interfaces/filesystem/path/dock_path.s: test/interfaces/filesystem/path/dock_path.cpp.s
.PHONY : test/interfaces/filesystem/path/dock_path.s

# target to generate assembly for a file
test/interfaces/filesystem/path/dock_path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/path/dock_path.cpp.s
.PHONY : test/interfaces/filesystem/path/dock_path.cpp.s

test/interfaces/filesystem/test_filenotfound.o: test/interfaces/filesystem/test_filenotfound.cpp.o
.PHONY : test/interfaces/filesystem/test_filenotfound.o

# target to build an object file
test/interfaces/filesystem/test_filenotfound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_filenotfound.cpp.o
.PHONY : test/interfaces/filesystem/test_filenotfound.cpp.o

test/interfaces/filesystem/test_filenotfound.i: test/interfaces/filesystem/test_filenotfound.cpp.i
.PHONY : test/interfaces/filesystem/test_filenotfound.i

# target to preprocess a source file
test/interfaces/filesystem/test_filenotfound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_filenotfound.cpp.i
.PHONY : test/interfaces/filesystem/test_filenotfound.cpp.i

test/interfaces/filesystem/test_filenotfound.s: test/interfaces/filesystem/test_filenotfound.cpp.s
.PHONY : test/interfaces/filesystem/test_filenotfound.s

# target to generate assembly for a file
test/interfaces/filesystem/test_filenotfound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_filenotfound.cpp.s
.PHONY : test/interfaces/filesystem/test_filenotfound.cpp.s

test/interfaces/filesystem/test_filesystem.o: test/interfaces/filesystem/test_filesystem.cpp.o
.PHONY : test/interfaces/filesystem/test_filesystem.o

# target to build an object file
test/interfaces/filesystem/test_filesystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_filesystem.cpp.o
.PHONY : test/interfaces/filesystem/test_filesystem.cpp.o

test/interfaces/filesystem/test_filesystem.i: test/interfaces/filesystem/test_filesystem.cpp.i
.PHONY : test/interfaces/filesystem/test_filesystem.i

# target to preprocess a source file
test/interfaces/filesystem/test_filesystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_filesystem.cpp.i
.PHONY : test/interfaces/filesystem/test_filesystem.cpp.i

test/interfaces/filesystem/test_filesystem.s: test/interfaces/filesystem/test_filesystem.cpp.s
.PHONY : test/interfaces/filesystem/test_filesystem.s

# target to generate assembly for a file
test/interfaces/filesystem/test_filesystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_filesystem.cpp.s
.PHONY : test/interfaces/filesystem/test_filesystem.cpp.s

test/interfaces/filesystem/test_paths.o: test/interfaces/filesystem/test_paths.cpp.o
.PHONY : test/interfaces/filesystem/test_paths.o

# target to build an object file
test/interfaces/filesystem/test_paths.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_paths.cpp.o
.PHONY : test/interfaces/filesystem/test_paths.cpp.o

test/interfaces/filesystem/test_paths.i: test/interfaces/filesystem/test_paths.cpp.i
.PHONY : test/interfaces/filesystem/test_paths.i

# target to preprocess a source file
test/interfaces/filesystem/test_paths.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_paths.cpp.i
.PHONY : test/interfaces/filesystem/test_paths.cpp.i

test/interfaces/filesystem/test_paths.s: test/interfaces/filesystem/test_paths.cpp.s
.PHONY : test/interfaces/filesystem/test_paths.s

# target to generate assembly for a file
test/interfaces/filesystem/test_paths.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_paths.cpp.s
.PHONY : test/interfaces/filesystem/test_paths.cpp.s

test/interfaces/filesystem/test_system.o: test/interfaces/filesystem/test_system.cpp.o
.PHONY : test/interfaces/filesystem/test_system.o

# target to build an object file
test/interfaces/filesystem/test_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_system.cpp.o
.PHONY : test/interfaces/filesystem/test_system.cpp.o

test/interfaces/filesystem/test_system.i: test/interfaces/filesystem/test_system.cpp.i
.PHONY : test/interfaces/filesystem/test_system.i

# target to preprocess a source file
test/interfaces/filesystem/test_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_system.cpp.i
.PHONY : test/interfaces/filesystem/test_system.cpp.i

test/interfaces/filesystem/test_system.s: test/interfaces/filesystem/test_system.cpp.s
.PHONY : test/interfaces/filesystem/test_system.s

# target to generate assembly for a file
test/interfaces/filesystem/test_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/filesystem/test_system.cpp.s
.PHONY : test/interfaces/filesystem/test_system.cpp.s

test/interfaces/language/dock_exceptions.o: test/interfaces/language/dock_exceptions.cpp.o
.PHONY : test/interfaces/language/dock_exceptions.o

# target to build an object file
test/interfaces/language/dock_exceptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/language/dock_exceptions.cpp.o
.PHONY : test/interfaces/language/dock_exceptions.cpp.o

test/interfaces/language/dock_exceptions.i: test/interfaces/language/dock_exceptions.cpp.i
.PHONY : test/interfaces/language/dock_exceptions.i

# target to preprocess a source file
test/interfaces/language/dock_exceptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/language/dock_exceptions.cpp.i
.PHONY : test/interfaces/language/dock_exceptions.cpp.i

test/interfaces/language/dock_exceptions.s: test/interfaces/language/dock_exceptions.cpp.s
.PHONY : test/interfaces/language/dock_exceptions.s

# target to generate assembly for a file
test/interfaces/language/dock_exceptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/language/dock_exceptions.cpp.s
.PHONY : test/interfaces/language/dock_exceptions.cpp.s

test/interfaces/language/test_exceptions.o: test/interfaces/language/test_exceptions.cpp.o
.PHONY : test/interfaces/language/test_exceptions.o

# target to build an object file
test/interfaces/language/test_exceptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/language/test_exceptions.cpp.o
.PHONY : test/interfaces/language/test_exceptions.cpp.o

test/interfaces/language/test_exceptions.i: test/interfaces/language/test_exceptions.cpp.i
.PHONY : test/interfaces/language/test_exceptions.i

# target to preprocess a source file
test/interfaces/language/test_exceptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/language/test_exceptions.cpp.i
.PHONY : test/interfaces/language/test_exceptions.cpp.i

test/interfaces/language/test_exceptions.s: test/interfaces/language/test_exceptions.cpp.s
.PHONY : test/interfaces/language/test_exceptions.s

# target to generate assembly for a file
test/interfaces/language/test_exceptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/language/test_exceptions.cpp.s
.PHONY : test/interfaces/language/test_exceptions.cpp.s

test/interfaces/renumber/dock_interface.o: test/interfaces/renumber/dock_interface.cpp.o
.PHONY : test/interfaces/renumber/dock_interface.o

# target to build an object file
test/interfaces/renumber/dock_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/renumber/dock_interface.cpp.o
.PHONY : test/interfaces/renumber/dock_interface.cpp.o

test/interfaces/renumber/dock_interface.i: test/interfaces/renumber/dock_interface.cpp.i
.PHONY : test/interfaces/renumber/dock_interface.i

# target to preprocess a source file
test/interfaces/renumber/dock_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/renumber/dock_interface.cpp.i
.PHONY : test/interfaces/renumber/dock_interface.cpp.i

test/interfaces/renumber/dock_interface.s: test/interfaces/renumber/dock_interface.cpp.s
.PHONY : test/interfaces/renumber/dock_interface.s

# target to generate assembly for a file
test/interfaces/renumber/dock_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/renumber/dock_interface.cpp.s
.PHONY : test/interfaces/renumber/dock_interface.cpp.s

test/interfaces/status/dock_StatusLine.o: test/interfaces/status/dock_StatusLine.cpp.o
.PHONY : test/interfaces/status/dock_StatusLine.o

# target to build an object file
test/interfaces/status/dock_StatusLine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/status/dock_StatusLine.cpp.o
.PHONY : test/interfaces/status/dock_StatusLine.cpp.o

test/interfaces/status/dock_StatusLine.i: test/interfaces/status/dock_StatusLine.cpp.i
.PHONY : test/interfaces/status/dock_StatusLine.i

# target to preprocess a source file
test/interfaces/status/dock_StatusLine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/status/dock_StatusLine.cpp.i
.PHONY : test/interfaces/status/dock_StatusLine.cpp.i

test/interfaces/status/dock_StatusLine.s: test/interfaces/status/dock_StatusLine.cpp.s
.PHONY : test/interfaces/status/dock_StatusLine.s

# target to generate assembly for a file
test/interfaces/status/dock_StatusLine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/status/dock_StatusLine.cpp.s
.PHONY : test/interfaces/status/dock_StatusLine.cpp.s

test/interfaces/status/test_StatusLine.o: test/interfaces/status/test_StatusLine.cpp.o
.PHONY : test/interfaces/status/test_StatusLine.o

# target to build an object file
test/interfaces/status/test_StatusLine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/status/test_StatusLine.cpp.o
.PHONY : test/interfaces/status/test_StatusLine.cpp.o

test/interfaces/status/test_StatusLine.i: test/interfaces/status/test_StatusLine.cpp.i
.PHONY : test/interfaces/status/test_StatusLine.i

# target to preprocess a source file
test/interfaces/status/test_StatusLine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/status/test_StatusLine.cpp.i
.PHONY : test/interfaces/status/test_StatusLine.cpp.i

test/interfaces/status/test_StatusLine.s: test/interfaces/status/test_StatusLine.cpp.s
.PHONY : test/interfaces/status/test_StatusLine.s

# target to generate assembly for a file
test/interfaces/status/test_StatusLine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/status/test_StatusLine.cpp.s
.PHONY : test/interfaces/status/test_StatusLine.cpp.s

test/interfaces/strings/test_ReplaceFirst.o: test/interfaces/strings/test_ReplaceFirst.cpp.o
.PHONY : test/interfaces/strings/test_ReplaceFirst.o

# target to build an object file
test/interfaces/strings/test_ReplaceFirst.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_ReplaceFirst.cpp.o
.PHONY : test/interfaces/strings/test_ReplaceFirst.cpp.o

test/interfaces/strings/test_ReplaceFirst.i: test/interfaces/strings/test_ReplaceFirst.cpp.i
.PHONY : test/interfaces/strings/test_ReplaceFirst.i

# target to preprocess a source file
test/interfaces/strings/test_ReplaceFirst.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_ReplaceFirst.cpp.i
.PHONY : test/interfaces/strings/test_ReplaceFirst.cpp.i

test/interfaces/strings/test_ReplaceFirst.s: test/interfaces/strings/test_ReplaceFirst.cpp.s
.PHONY : test/interfaces/strings/test_ReplaceFirst.s

# target to generate assembly for a file
test/interfaces/strings/test_ReplaceFirst.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_ReplaceFirst.cpp.s
.PHONY : test/interfaces/strings/test_ReplaceFirst.cpp.s

test/interfaces/strings/test_ReplaceLast.o: test/interfaces/strings/test_ReplaceLast.cpp.o
.PHONY : test/interfaces/strings/test_ReplaceLast.o

# target to build an object file
test/interfaces/strings/test_ReplaceLast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_ReplaceLast.cpp.o
.PHONY : test/interfaces/strings/test_ReplaceLast.cpp.o

test/interfaces/strings/test_ReplaceLast.i: test/interfaces/strings/test_ReplaceLast.cpp.i
.PHONY : test/interfaces/strings/test_ReplaceLast.i

# target to preprocess a source file
test/interfaces/strings/test_ReplaceLast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_ReplaceLast.cpp.i
.PHONY : test/interfaces/strings/test_ReplaceLast.cpp.i

test/interfaces/strings/test_ReplaceLast.s: test/interfaces/strings/test_ReplaceLast.cpp.s
.PHONY : test/interfaces/strings/test_ReplaceLast.s

# target to generate assembly for a file
test/interfaces/strings/test_ReplaceLast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_ReplaceLast.cpp.s
.PHONY : test/interfaces/strings/test_ReplaceLast.cpp.s

test/interfaces/strings/test_Split.o: test/interfaces/strings/test_Split.cpp.o
.PHONY : test/interfaces/strings/test_Split.o

# target to build an object file
test/interfaces/strings/test_Split.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_Split.cpp.o
.PHONY : test/interfaces/strings/test_Split.cpp.o

test/interfaces/strings/test_Split.i: test/interfaces/strings/test_Split.cpp.i
.PHONY : test/interfaces/strings/test_Split.i

# target to preprocess a source file
test/interfaces/strings/test_Split.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_Split.cpp.i
.PHONY : test/interfaces/strings/test_Split.cpp.i

test/interfaces/strings/test_Split.s: test/interfaces/strings/test_Split.cpp.s
.PHONY : test/interfaces/strings/test_Split.s

# target to generate assembly for a file
test/interfaces/strings/test_Split.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/interfaces/strings/test_Split.cpp.s
.PHONY : test/interfaces/strings/test_Split.cpp.s

test/vendor/dock_FakeIt.o: test/vendor/dock_FakeIt.cpp.o
.PHONY : test/vendor/dock_FakeIt.o

# target to build an object file
test/vendor/dock_FakeIt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/vendor/dock_FakeIt.cpp.o
.PHONY : test/vendor/dock_FakeIt.cpp.o

test/vendor/dock_FakeIt.i: test/vendor/dock_FakeIt.cpp.i
.PHONY : test/vendor/dock_FakeIt.i

# target to preprocess a source file
test/vendor/dock_FakeIt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/vendor/dock_FakeIt.cpp.i
.PHONY : test/vendor/dock_FakeIt.cpp.i

test/vendor/dock_FakeIt.s: test/vendor/dock_FakeIt.cpp.s
.PHONY : test/vendor/dock_FakeIt.s

# target to generate assembly for a file
test/vendor/dock_FakeIt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/vendor/dock_FakeIt.cpp.s
.PHONY : test/vendor/dock_FakeIt.cpp.s

test/vendor/main.o: test/vendor/main.cpp.o
.PHONY : test/vendor/main.o

# target to build an object file
test/vendor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/vendor/main.cpp.o
.PHONY : test/vendor/main.cpp.o

test/vendor/main.i: test/vendor/main.cpp.i
.PHONY : test/vendor/main.i

# target to preprocess a source file
test/vendor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/vendor/main.cpp.i
.PHONY : test/vendor/main.cpp.i

test/vendor/main.s: test/vendor/main.cpp.s
.PHONY : test/vendor/main.s

# target to generate assembly for a file
test/vendor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run-unittests-extras.dir/build.make CMakeFiles/run-unittests-extras.dir/test/vendor/main.cpp.s
.PHONY : test/vendor/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... extras"
	@echo "... run-unittests-extras"
	@echo "... src/crcs/crc.o"
	@echo "... src/crcs/crc.i"
	@echo "... src/crcs/crc.s"
	@echo "... src/crcs/crc16.o"
	@echo "... src/crcs/crc16.i"
	@echo "... src/crcs/crc16.s"
	@echo "... src/crcs/crc32.o"
	@echo "... src/crcs/crc32.i"
	@echo "... src/crcs/crc32.s"
	@echo "... src/crcs/crc64.o"
	@echo "... src/crcs/crc64.i"
	@echo "... src/crcs/crc64.s"
	@echo "... src/devices/ansi_colors.o"
	@echo "... src/devices/ansi_colors.i"
	@echo "... src/devices/ansi_colors.s"
	@echo "... src/devices/dotenv.o"
	@echo "... src/devices/dotenv.i"
	@echo "... src/devices/dotenv.s"
	@echo "... src/exceptions.o"
	@echo "... src/exceptions.i"
	@echo "... src/exceptions.s"
	@echo "... src/file/assertions.o"
	@echo "... src/file/assertions.i"
	@echo "... src/file/assertions.s"
	@echo "... src/file/construct.o"
	@echo "... src/file/construct.i"
	@echo "... src/file/construct.s"
	@echo "... src/file/methods.o"
	@echo "... src/file/methods.i"
	@echo "... src/file/methods.s"
	@echo "... src/filesystem/files.o"
	@echo "... src/filesystem/files.i"
	@echo "... src/filesystem/files.s"
	@echo "... src/filesystem/filesystem.o"
	@echo "... src/filesystem/filesystem.i"
	@echo "... src/filesystem/filesystem.s"
	@echo "... src/filesystem/paths.o"
	@echo "... src/filesystem/paths.i"
	@echo "... src/filesystem/paths.s"
	@echo "... src/filesystem/system.o"
	@echo "... src/filesystem/system.i"
	@echo "... src/filesystem/system.s"
	@echo "... src/status/StatusLine.o"
	@echo "... src/status/StatusLine.i"
	@echo "... src/status/StatusLine.s"
	@echo "... src/strings/string_support.o"
	@echo "... src/strings/string_support.i"
	@echo "... src/strings/string_support.s"
	@echo "... src/strings/strings.o"
	@echo "... src/strings/strings.i"
	@echo "... src/strings/strings.s"
	@echo "... test/interfaces/crcs/dock_octal.o"
	@echo "... test/interfaces/crcs/dock_octal.i"
	@echo "... test/interfaces/crcs/dock_octal.s"
	@echo "... test/interfaces/crcs/test_crc32.o"
	@echo "... test/interfaces/crcs/test_crc32.i"
	@echo "... test/interfaces/crcs/test_crc32.s"
	@echo "... test/interfaces/crcs/test_crc64.o"
	@echo "... test/interfaces/crcs/test_crc64.i"
	@echo "... test/interfaces/crcs/test_crc64.s"
	@echo "... test/interfaces/crcs/test_crcs.o"
	@echo "... test/interfaces/crcs/test_crcs.i"
	@echo "... test/interfaces/crcs/test_crcs.s"
	@echo "... test/interfaces/devices/dock_dotenv.o"
	@echo "... test/interfaces/devices/dock_dotenv.i"
	@echo "... test/interfaces/devices/dock_dotenv.s"
	@echo "... test/interfaces/devices/test_dotenv.o"
	@echo "... test/interfaces/devices/test_dotenv.i"
	@echo "... test/interfaces/devices/test_dotenv.s"
	@echo "... test/interfaces/etc/dock_interface.o"
	@echo "... test/interfaces/etc/dock_interface.i"
	@echo "... test/interfaces/etc/dock_interface.s"
	@echo "... test/interfaces/file/dock_interface.o"
	@echo "... test/interfaces/file/dock_interface.i"
	@echo "... test/interfaces/file/dock_interface.s"
	@echo "... test/interfaces/file/mold_assertions.o"
	@echo "... test/interfaces/file/mold_assertions.i"
	@echo "... test/interfaces/file/mold_assertions.s"
	@echo "... test/interfaces/file/test_cases.o"
	@echo "... test/interfaces/file/test_cases.i"
	@echo "... test/interfaces/file/test_cases.s"
	@echo "... test/interfaces/filesystem/dock_paths.o"
	@echo "... test/interfaces/filesystem/dock_paths.i"
	@echo "... test/interfaces/filesystem/dock_paths.s"
	@echo "... test/interfaces/filesystem/path/dock_path.o"
	@echo "... test/interfaces/filesystem/path/dock_path.i"
	@echo "... test/interfaces/filesystem/path/dock_path.s"
	@echo "... test/interfaces/filesystem/test_filenotfound.o"
	@echo "... test/interfaces/filesystem/test_filenotfound.i"
	@echo "... test/interfaces/filesystem/test_filenotfound.s"
	@echo "... test/interfaces/filesystem/test_filesystem.o"
	@echo "... test/interfaces/filesystem/test_filesystem.i"
	@echo "... test/interfaces/filesystem/test_filesystem.s"
	@echo "... test/interfaces/filesystem/test_paths.o"
	@echo "... test/interfaces/filesystem/test_paths.i"
	@echo "... test/interfaces/filesystem/test_paths.s"
	@echo "... test/interfaces/filesystem/test_system.o"
	@echo "... test/interfaces/filesystem/test_system.i"
	@echo "... test/interfaces/filesystem/test_system.s"
	@echo "... test/interfaces/language/dock_exceptions.o"
	@echo "... test/interfaces/language/dock_exceptions.i"
	@echo "... test/interfaces/language/dock_exceptions.s"
	@echo "... test/interfaces/language/test_exceptions.o"
	@echo "... test/interfaces/language/test_exceptions.i"
	@echo "... test/interfaces/language/test_exceptions.s"
	@echo "... test/interfaces/renumber/dock_interface.o"
	@echo "... test/interfaces/renumber/dock_interface.i"
	@echo "... test/interfaces/renumber/dock_interface.s"
	@echo "... test/interfaces/status/dock_StatusLine.o"
	@echo "... test/interfaces/status/dock_StatusLine.i"
	@echo "... test/interfaces/status/dock_StatusLine.s"
	@echo "... test/interfaces/status/test_StatusLine.o"
	@echo "... test/interfaces/status/test_StatusLine.i"
	@echo "... test/interfaces/status/test_StatusLine.s"
	@echo "... test/interfaces/strings/test_ReplaceFirst.o"
	@echo "... test/interfaces/strings/test_ReplaceFirst.i"
	@echo "... test/interfaces/strings/test_ReplaceFirst.s"
	@echo "... test/interfaces/strings/test_ReplaceLast.o"
	@echo "... test/interfaces/strings/test_ReplaceLast.i"
	@echo "... test/interfaces/strings/test_ReplaceLast.s"
	@echo "... test/interfaces/strings/test_Split.o"
	@echo "... test/interfaces/strings/test_Split.i"
	@echo "... test/interfaces/strings/test_Split.s"
	@echo "... test/vendor/dock_FakeIt.o"
	@echo "... test/vendor/dock_FakeIt.i"
	@echo "... test/vendor/dock_FakeIt.s"
	@echo "... test/vendor/main.o"
	@echo "... test/vendor/main.i"
	@echo "... test/vendor/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/perry/dev/extras/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

